' p.55 Curve Fit - Parabolic
10 "CFP" CLEAR : GOTO 30
20 H=H+XXXX : I=I+Y : J=J+XY : K=K+XXY : L=L+YY
30 BEEP 1 : INPUT "X?",X,"Y?",Y : D=D+1 : E=E+X : F=F+XX : G=G+XXX : GOTO 20
40 M=DFH+2EGF-FFF-EEH-DGG : A=(HFI+EGK+FJG-FFK-EJH-IGG)/M
50 B=(DJH+IGF+FEK-FJF-IEH-DGK)/M : C=(DFK+EJF+IEG-FFI-EEK-DJG)/M
60 R=(AI+BJ+CK-II/D)/(L-II/D) : PRINT "Y=A+BX+CX^2"
70 PRINT "A=";A : PRINT "B=";B : PRINT "C=";C : PRINT "R^2=";R
80 INPUT "NEW X?",X : PRINT A+BX+CXX : GOTO 80
90 GOTO 1
