' p.23 Checkbook
10 "CHECKS" USING "######.##" : INPUT "BEGINNING BALANCE?",A : B=A
20 INPUT "CHECK? ";C : A=A-C : B=B-C : GOTO 20
30 INPUT "DEPOSIT? ";D : A=A+D : B=B+D : GOTO 20
40 INPUT "UNCLEARED CHECK? ";E : A=A-E : GOTO 20
50 INPUT "UNCLEARED DEPOSIT? ";F : A=A+F : GOTO 20
60 BEEP 1 : PRINT "BOOK SHOULD SAY";A
70 BEEP 1 : PRINT "BANK SHOULD SAY";B : GOTO 20
