' p.173 Matrix Inversion [ARRAY]
10 "MATI" CLEAR : INPUT "SIZE?",A : A(2AA+8)=0 : B=AA+8 : FOR E=1 TO A : FOR F=1 TO A : B=B+1 : A(B)=(E=F)
20 INPUT A(EA+F-A+8) : NEXT F : NEXT E : GOTO 40
30 PAUSE "DOWN";A;" ACROSS";F : GOTO 20
40 FOR F=1 TO A : E=F
50 IF ABS A(EA+F-A+8) GOTO 80
60 E=E+1 : IF E<=A THEN 50
70 PRINT "SINGULAR" : GOTO 1
80 FOR G=1 TO A : B=FA+G-A+8 : C=EA+G-A+8 : D=A(B) : A(B)=A(C) : A(C)=D
90 B=B+AA : C=C+AA : D=A(B) : A(B)=A(C) : A(C)=D : NEXT G
100 B=A(FA+F-A+8) : FOR G=1 TO A : C=FA+G-A+8 : D=C+AA : A(C)=A(C)/B
110 A(D)=A(D)/B : NEXT G : FOR H=1 TO A : IF H=F THEN 140
120 B=A(HA+F-A+8) : FOR G=1 TO A : C=HA+G-A+8 : D=FA+G-A+8
130 A(C)=A(C)-BA(D) : C=C+AA : A(C)=A(C)-BA(D+AA) : NEXT G
140 NEXT H : NEXT F : BEEP 1
150 "MATOUT" FOR E=1 TO A : FOR F=1 TO A : B=EA+F-A+8+AA : PRINT E;F;")=";A(B) : NEXT F : NEXT E : GOTO 1
