' p.189 Moving Average [ARRAY]
10 "MAV" CLEAR : INPUT "HOW MANY EACH AVERAGE?",A : C=5
20 C=C+1 : IF C>5+A LET C=6
30 D=D-A(C) : INPUT "VALUE?",A(C) : D=D+A(C)
40 E=D/A : B=B+1 : IF B<A PRINT "THAT WAS ENTRY #";B : GOTO 20
50 PRINT "MOVING AVE=";E : GOTO 20
