' p.227 Polygons - Regular
10 "POLY" CLEAR : A=4*ATN 1
20 INPUT "# SIDES?",N
30 INPUT "LEN SIZE?",S
40 IF NS=0 INPUT "INSCRIBED RADIUS?",I
50 IF NS+SI+NI=0 INPUT "CIRCUMSCRIBED RADIUS?",R
60 IF NS LET I=S/2/TAN(A/N)
70 IF NI LET S=2I*TAN(A/N)
80 IF SI LET N=A/ATN(S/2I)
90 IF NR LET S=2R*SIN(A/N)
100 IF SR LET N=A/ASN(S/2R)
110 IF IR LET N=A/ACS(I/R)
120 IF NSI=0 THEN 60
130 A=A/N : PRINT N;" SIDES" : PRINT S;" SIDE LEN"
140 PRINT I; " INS RAD" : PRINT S/2/SIN A;" CIR RAD"
150 PRINT SN;" PERIMETER" : PRINT AN-2A;" VERTEX ANGLE"
160 PRINT NII*TAN A;" AREA" : GOTO 1
