' p.235 Radioisotope Activity
10 "RAD" CLEAR : INPUT "START ACTIVITY?",A
20 INPUT "HALF-LIFE?",H
30 INPUT "ELAPSED TIME?",T
40 IF AHT=0 INPUT "FINAL ACTIVITY?",B
50 IF A=0 LET A=B/.5^(T/H) : PRINT "ST ACT=";A
60 IF H=0 LET H=T*LN .5/LN(B/A) : PRINT "HALFLF=";H
70 IF T=0 LET T=H*LN(B/A)/LN .5 : PRINT "TIME=";T
80 IF B=0 LET B=A*.5^(T/H) : PRINT "END ACT=";B
90 GOTO 1
