' p.247 Relativity
10 "REL" C=2.99776[E]8
20 INPUT "VEL?",V : G=1/[SQR](1-VV/CC) : GOTO 40
30 INPUT "GAMMA?",G : V=[SQR](CC-CC/GG)
40 B=V/C : INPUT "LEN?",L : Y=LG : PRINT L/G,Y : GOTO 70
50 INPUT "TIME?",T : Y=T/G : PRINT TG,Y : GOTO 70
60 INPUT "MASS?",M : Y=M/G : PRINT MG,Y
70 PRINT "VEL=";V : PRINT "V/C=";B : PRINT "GAMMA=";G : GOTO 1
