' p.251 Simultaneous Equations - Size Three
10 "SE3" FOR I=1 TO 3 : BEEP 1 : PAUSE "EQ #";I : FOR J=1 TO 4 : INPUT A(4I+J+10) : NEXT J : NEXT I
20 D=OTY+PUW+QSX-QTW-PSY-OUX : A=(RTY+PUZ+QVX-QTZ-PVY-RUX)/D
30 B=(OVY+RUW+QSZ-QVW-RSY-OUZ)/D : C=(OTZ+PVW+RSX-RTW-PSZ-OVX)/D
40 PRINT "1)=";A : PRINT "2)=";B : PRINT "3)=";C : GOTO 1
