' p.141 Hyperbolic Functions
10 "SINH" INPUT X : PRINT (EXP X-EXP -X)/2 : GOTO 1
20 "COSH" INPUT X : PRINT (EXP X+EXP -X)/2 : GOTO 1
30 "TANH" INPUT X : PRINT (EXP X-EXP -X)/(EXP X+EXP -X) : GOTO 1
40 "ASNH" INPUT X : PRINT LN(X+[SQR](XX+1)) : GOTO 1
50 "ACSH" INPUT X : PRINT LN(X+[SQR](XX-1)) : GOTO 1
60 "ATNH" INPUT X : PRINT LN((1+X)/(1-X))/2 : GOTO 1
